const $=id=>document.getElementById(id);let stream=null,result=null,rows=null,entries=[];const setStatus=s=>$('status').textContent=s;
function stop(){stream?.getTracks().forEach(t=>t.stop());stream=null;$('video').srcObject=null;$('video').hidden=true;$('capture').disabled=true;$('stop').disabled=true;if($('shot').hidden)$('empty').hidden=false;setStatus('Screen sharing stopped.');}
$('share').onclick=async()=>{try{if(!navigator.mediaDevices?.getDisplayMedia)throw Error('Use a desktop browser that supports screen sharing.');stream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false});$('video').srcObject=stream;$('video').hidden=false;$('shot').hidden=true;$('empty').hidden=true;$('capture').disabled=false;$('stop').disabled=false;stream.getVideoTracks()[0].addEventListener('ended',stop,{once:true});setStatus('Screen sharing active. The chart is not being interpreted yet.');}catch(e){setStatus(e.name==='NotAllowedError'?'Screen sharing did not start. You can try again.':e.message);}};
$('stop').onclick=stop;$('capture').onclick=()=>{const v=$('video');if(!v.videoWidth){setStatus('Wait for the stream to load.');return}const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);$('shot').src=c.toDataURL('image/png');$('shot').hidden=false;stop();$('empty').hidden=true;setStatus('Capture ready. Automatic visual analysis is not connected.');};
$('image').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(!f.type.startsWith('image/'))return setStatus('Select an image.');if(f.size>10*1024*1024)return setStatus('The image must be smaller than 10 MB.');stop();const old=$('shot').src;if(old.startsWith('blob:'))URL.revokeObjectURL(old);$('shot').src=URL.createObjectURL(f);$('shot').hidden=false;$('empty').hidden=true;setStatus('Image loaded. No prices or signals have been extracted from it.');};
function parseCSV(text){const lines=text.trim().split(/\r?\n/);const cols=lines.shift().replace(/^\uFEFF/,'').toLowerCase().split(',').map(s=>s.trim());for(const x of ['time','open','high','low','close'])if(!cols.includes(x))throw Error('Missing column: '+x);const data=lines.filter(s=>s.trim()).map((s,i)=>{const a=s.split(',');const r={};cols.forEach((k,j)=>r[k]=k==='time'?a[j]?.trim():Number(a[j]));if(!r.time||['open','high','low','close'].some(k=>!Number.isFinite(r[k])||r[k]<=0)||r.low>Math.min(r.open,r.close)||r.high<Math.max(r.open,r.close)||r.high<r.low)throw Error('Invalid prices on row '+(i+2));r.timestamp=/^\d+(\.\d+)?$/.test(r.time)?Number(r.time)*(Number(r.time)<1e12?1000:1):Date.parse(r.time);if(!Number.isFinite(r.timestamp))throw Error('Invalid date on row '+(i+2));if(r.volume!==undefined&&(!Number.isFinite(r.volume)||r.volume<0))throw Error('Invalid volume');return r;});if(data.length<30)throw Error('Import at least 30 closed candles.');if(data.some((r,i)=>i&&r.timestamp<=data[i-1].timestamp))throw Error('Candles must be chronological without duplicates.');return data;}
function evaluate(data){const last=data.at(-1),prev=data.slice(-21,-1),hi=Math.max(...prev.map(x=>x.high)),lo=Math.min(...prev.map(x=>x.low));const avg=a=>a.reduce((s,x)=>s+x,0)/a.length;const ma=avg(data.slice(-20).map(x=>x.close)),oldma=avg(data.slice(-21,-1).map(x=>x.close));const atr=avg(data.slice(-14).map((r,j)=>{const p=data[data.length-15+j].close;return Math.max(r.high-r.low,Math.abs(r.high-p),Math.abs(r.low-p))}));let side=last.close>hi&&ma>oldma?'Buy':last.close<lo&&ma<oldma?'Sell':'Wait';return {side,entry:last.close,atr,sl:side==='Buy'?last.close-atr:last.close+atr,tp:side==='Buy'?last.close+2*atr:last.close-2*atr,reason:side==='Wait'?'No confirmed breakout under the initial rules. Watch the high '+hi.toFixed(4)+' and the low '+lo.toFixed(4)+'.':'The latest close broke the 20-candle range in the moving average direction. Experimental signal, without a validated probability.'};}
function pnl(){if(!result||result.side==='Wait')return $('pnl').textContent='No active entry for calculating scenarios.';const u=Number($('units').value),c=Number($('cost').value);if(!Number.isFinite(u)||!Number.isFinite(c)||u<=0||c<0)return $('pnl').textContent='Enter positive units and nonnegative costs.';$('pnl').textContent='At target: '+(2*result.atr*u-c).toFixed(2)+' · At stop: −'+(result.atr*u+c).toFixed(2)+' (quote currency).';}
function analyze(){if(!rows)return;result=evaluate(rows);$('signal').textContent=result.side;$('reason').textContent=result.reason;const active=result.side!=='Wait';['entry','sl','tp'].forEach(k=>$(k).textContent=active?result[k].toFixed(4):'—');const gaps=rows.slice(1).map((r,i)=>r.timestamp-rows[i].timestamp).sort((a,b)=>a-b);const step=gaps[Math.floor(gaps.length/2)];$('expiry').textContent='From '+new Date(rows.at(-1).timestamp+step).toLocaleTimeString()+' to '+new Date(rows.at(-1).timestamp+step+1800000).toLocaleTimeString();const item=new Date().toLocaleTimeString()+' · '+($('asset').value.trim()||'Unidentified asset')+' · '+$('tf').value+' · '+result.side;entries.unshift(item);$('log').replaceChildren(...entries.slice(0,20).map(s=>{const li=document.createElement('li');li.textContent=s;return li}));updateLearning();pnl();setStatus(rows.length+' candles imported. Last candle: '+rows.at(-1).time+'. File analysis, not live prices.');}
$('csv').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>5*1024*1024)throw Error('CSV too large; maximum 5 MB.');const parsed=parseCSV(await f.text());rows=parsed;drawChart(rows);analyze();}catch(err){setStatus(err.message);}};['units','cost'].forEach(k=>$(k).oninput=pnl);['tf','asset'].forEach(k=>$(k).onchange=()=>{rows=null;result=null;$('signal').textContent='Wait';$('reason').textContent='Import prices for the new asset and timeframe.';['entry','sl','tp','expiry'].forEach(k=>$(k).textContent='—');$('pnl').textContent='Import prices to calculate scenarios.';setStatus('Selection changed. Import a new CSV.');});
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'read_analysis',description:'Read the visible analysis and validation status',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:input=>{if(!input||Object.keys(input).length)throw Error('No parameters accepted');return {asset:$('asset').value,timeframe:$('tf').value,result,probabilities:'experimental',horizonMinutes:30,live:monitorTimer!==null}}});}catch(e){console.warn('WebMCP no disponible')}}

let monitorTimer=null,monitorEpoch=0,lastCandle=null,monitorBusy=false;
const tfMinutes={'1 minute':1,'5 minutes':5,'15 minutes':15,'30 minutes':30,'1 hour':60};
function historyStats(data,h,side){const counts={up:0,down:0,flat:0,n:0};for(let i=29;i+h<data.length;i+=h){const e=evaluate(data.slice(0,i+1));if(e.side!==side||e.atr<=0)continue;const delta=data[i+h].close-data[i].close;counts[delta>e.atr*.25?'up':delta< -e.atr*.25?'down':'flat']++;counts.n++;}return counts;}
function forecast30(data){
 const diffs=data.slice(1).map((r,i)=>r.timestamp-data[i].timestamp),sorted=[...diffs].sort((a,b)=>a-b),step=sorted[Math.floor(sorted.length/2)],h=1800000/step;
 if(!Number.isFinite(h)||h<1||!Number.isInteger(h))return {available:false,reason:'A 30-minute forecast requires 1, 5, 15 or 30-minute candles. Hourly candles do not contain the intermediate close.'};
 const feature=i=>{const window=data.slice(i-20,i+1),e=evaluate(data.slice(0,i+1)),atr=e.atr||1;const closes=window.map(r=>r.close),avg=closes.slice(-20).reduce((s,v)=>s+v,0)/20,hi=Math.max(...window.map(r=>r.high)),lo=Math.min(...window.map(r=>r.low));return [1,(data[i].close-data[i-3].close)/atr,(data[i].close-avg)/atr,(data[i].close-lo)/(hi-lo||1)-.5];};
 const samples=[];for(let i=29;i+h<data.length;i+=h){if(data[i+h].timestamp-data[i].timestamp!==1800000)continue;let regular=true;for(let j=i+1;j<=i+h;j++)if(data[j].timestamp-data[j-1].timestamp!==step){regular=false;break;}if(!regular)continue;const d=data[i+h].close-data[i].close;if(d!==0)samples.push({x:feature(i),y:d>0?1:0});}
 const split=Math.floor(samples.length*.7),train=samples.slice(0,split),test=samples.slice(split);if(train.length<60||test.length<30)return {available:false,reason:samples.length+' known 30-minute outcomes; at least 60 training and 30 test examples are required. Unchanged closes are excluded.'};
 const means=[0,0,0,0],scales=[1,1,1,1];for(let k=1;k<4;k++){means[k]=train.reduce((s,r)=>s+r.x[k],0)/train.length;scales[k]=Math.sqrt(train.reduce((s,r)=>s+(r.x[k]-means[k])**2,0)/train.length)||1;}
 const norm=x=>x.map((v,k)=>k?(v-means[k])/scales[k]:v),sig=z=>1/(1+Math.exp(-Math.max(-35,Math.min(35,z))));const fit=list=>{const w=[0,0,0,0];for(let it=0;it<300;it++){const g=[0,0,0,0];for(const r of list){const x=norm(r.x),p=sig(w.reduce((s,v,k)=>s+v*x[k],0));x.forEach((v,k)=>g[k]+=(p-r.y)*v);}w.forEach((v,k)=>w[k]-=.08*(g[k]/list.length+(k?.01*v:0)));}return x=>sig(w.reduce((s,v,k)=>s+v*norm(x)[k],0));};
 const predict=fit(train),baseline=train.reduce((s,r)=>s+r.y,0)/train.length,brier=test.reduce((s,r)=>s+(predict(r.x)-r.y)**2,0)/test.length,baseBrier=test.reduce((s,r)=>s+(baseline-r.y)**2,0)/test.length;
 if(brier>=baseBrier)return {available:false,reason:'The model does not beat the historical baseline in chronological testing. Entry probabilities are withheld. Test: '+test.length+' examples; Brier '+brier.toFixed(3)+' versus '+baseBrier.toFixed(3)+'.'};
 // Refit after evaluation using only samples whose future outcome is already observed.
 const p=fit(samples)(feature(data.length-1));return {available:true,up:p,down:1-p,n:samples.length,test:test.length,brier,baseBrier};
}
function updateLearning(){if(!rows||!result)return;const v=forecast30(rows);$('upfreq').textContent='Not validated';$('downfreq').textContent='Not validated';if(!v.available){$('learning').textContent=v.reason;$('forecastDirection').textContent='No reliable directional estimate: '+v.reason;return;}$('forecastDirection').textContent=(v.up>.55?'Expected direction: higher':v.down>.55?'Expected direction: lower':'Expected direction: unclear')+' · Next 30 minutes from the latest known close · Experimental estimate.';$('upfreq').textContent=(v.up*100).toFixed(1)+'% estimated';$('downfreq').textContent=(v.down*100).toFixed(1)+'% estimated';$('learning').textContent='Close at +30 minutes relative to the latest close. '+v.n+' examples · Chronological test: '+v.test+' · Brier '+v.brier.toFixed(3)+' / baseline '+v.baseBrier.toFixed(3)+'. Experimental estimate, not externally calibrated. Unchanged closes are excluded; this is not a profit or loss forecast.';}
function haltMonitor(){$('forecastDirection').textContent='Forecast unavailable: load or refresh price history.';monitorEpoch++;clearTimeout(monitorTimer);monitorTimer=null;$('live').disabled=false;$('pauseLive').disabled=true;lastCandle=null;monitorBusy=false;$('liveStatus').textContent='Monitoring stopped.';}
function drawChart(data){const c=$('chart');c.hidden=false;c.width=Math.max(300,Math.floor(c.parentElement.clientWidth-40))*2;c.height=420;const ctx=c.getContext('2d'),values=data.slice(-80).map(r=>r.close),min=Math.min(...values),max=Math.max(...values);ctx.clearRect(0,0,c.width,c.height);ctx.strokeStyle='#3be5af';ctx.lineWidth=3;ctx.beginPath();values.forEach((v,i)=>{const x=20+i/(values.length-1)*(c.width-40),y=30+(1-(v-min)/(max-min||1))*350;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle='#b6c5d8';ctx.font='24px system-ui';ctx.fillText(max.toFixed(2),20,24);ctx.fillText(min.toFixed(2),20,412);}
async function pollMarket(epoch){if(epoch!==monitorEpoch||monitorBusy)return;monitorBusy=true;const pair=$('pair').value,interval=$('tf').value==='1 hour'?5:tfMinutes[$('tf').value];try{const response=await fetch('https://api.kraken.com/0/public/OHLC?pair='+encodeURIComponent(pair)+'&interval='+interval,{signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error('Data source returned '+response.status);const payload=await response.json();if(payload.error?.length)throw Error(payload.error.join(', '));const key=Object.keys(payload.result||{}).find(k=>k!=='last');if(!key)throw Error('The source returned no candles.');const raw=payload.result[key].slice(0,-1);const csv='time,open,high,low,close,volume\n'+raw.map(r=>[new Date(Number(r[0])*1000).toISOString(),r[1],r[2],r[3],r[4],r[6]].join(',')).join('\n');const data=parseCSV(csv);if(epoch!==monitorEpoch)return;const age=Date.now()-Date.parse(data.at(-1).time);if(age>(interval*3+2)*60000)throw Error('Prices are stale. No alerts will be generated.');rows=data;drawChart(rows);if(rows.at(-1).time!==lastCandle){const was=lastCandle;lastCandle=rows.at(-1).time;analyze();if(was&&result.side!=='Wait'&&$('notify').checked&&'Notification' in window&&Notification.permission==='granted')new Notification('Making Money · '+result.side,{body:pair+' · '+$('tf').value+' · Experimental signal. Check the app.'});}setStatus('Source: Kraken · '+pair+' · Data interval: '+interval+' minutes · Latest candle '+rows.at(-1).time);$('liveStatus').textContent='Monitoring active · Updated '+new Date().toLocaleTimeString()+' · Next check in 30 seconds.';}catch(e){if(epoch!==monitorEpoch)return;$('liveStatus').textContent='Update failed: '+e.message+'. Retrying in 30 seconds.';$('signal').textContent='Wait';$('reason').textContent='Source unavailable: the previous analysis is not a valid current entry.';result=null;['entry','sl','tp','expiry'].forEach(k=>$(k).textContent='—');$('upfreq').textContent='Not current';$('downfreq').textContent='Not current';pnl();}finally{if(epoch===monitorEpoch){monitorBusy=false;monitorTimer=setTimeout(()=>pollMarket(epoch),30000);}}}
$('live').onclick=()=>{haltMonitor();if($('pair').value==='XAUUSD'){setStatus('Gold: import XAU/USD CSV data. The live price source is not connected.');return;}$('asset').value=$('pair').value;rows=null;result=null;$('live').disabled=true;$('pauseLive').disabled=false;$('liveStatus').textContent='Loading prices…';pollMarket(monitorEpoch);};$('pauseLive').onclick=haltMonitor;
$('notify').onchange=async()=>{if(!$('notify').checked)return;if(!('Notification'in window)){$('notify').checked=false;$('liveStatus').textContent='This browser does not support notifications.';return;}const permission=await Notification.requestPermission();if(permission!=='granted'){$('notify').checked=false;$('liveStatus').textContent='Notifications not allowed. The in-app log remains available.';}};
for(const id of ['tf','asset','pair'])$(id).addEventListener('change',()=>{haltMonitor();rows=null;result=null;$('signal').textContent='Wait';$('reason').textContent='Selection changed. Load the corresponding source.';['entry','sl','tp','expiry'].forEach(k=>$(k).textContent='—');pnl();$('learning').textContent='Select the new source for evaluation.';$('upfreq').textContent='No sample';$('downfreq').textContent='No sample';$('chart').hidden=true;});
$('csv').addEventListener('change',haltMonitor);window.addEventListener('pagehide',haltMonitor);

$('pair').addEventListener('change',()=>{const gold=$('pair').value==='XAUUSD';$('goldInfo').hidden=!gold;$('live').disabled=gold;$('asset').value=$('pair').value;$('liveStatus').textContent=gold?'Gold selected · import an XAU/USD CSV.':'Kraken · checks every 30 seconds while the page is open.';});

let goldWidgetInterval=null;
const chartMarkets={XAUUSD:{symbol:'OANDA:XAUUSD',label:'XAU/USD',url:'https://www.tradingview.com/symbols/XAUUSD/'},XBTUSD:{symbol:'KRAKEN:BTCUSD',label:'BTC/USD',url:'https://www.tradingview.com/symbols/BTCUSD/?exchange=KRAKEN'},ETHUSD:{symbol:'KRAKEN:ETHUSD',label:'ETH/USD',url:'https://www.tradingview.com/symbols/ETHUSD/?exchange=KRAKEN'},SOLUSD:{symbol:'KRAKEN:SOLUSD',label:'SOL/USD',url:'https://www.tradingview.com/symbols/SOLUSD/?exchange=KRAKEN'}};
function showGoldChart(){const market=chartMarkets[$('pair').value];$('goldChart').hidden=false;const interval=String(tfMinutes[$('tf').value]);const identity=market.symbol+'|'+interval+'|'+document.documentElement.lang;if(goldWidgetInterval===identity)return;goldWidgetInterval=identity;$('chartFallback').href=market.url;const host=$('goldWidget');host.replaceChildren();const container=document.createElement('div');container.className='tradingview-widget-container';container.style.height='100%';container.style.width='100%';const widget=document.createElement('div');widget.className='tradingview-widget-container__widget';widget.style.height='calc(100% - 32px)';widget.style.width='100%';container.appendChild(widget);const credit=document.createElement('div');credit.className='tradingview-widget-copyright';const link=document.createElement('a');link.href=market.url;link.target='_blank';link.rel='noopener nofollow';link.textContent=market.label+' chart by TradingView';credit.appendChild(link);container.appendChild(credit);const script=document.createElement('script');script.src='https://s3.tradingview.com/external-embedding/embed-widget-advanced-chart.js';script.async=true;script.textContent=JSON.stringify({autosize:true,symbol:market.symbol,interval,timezone:'Etc/UTC',theme:'dark',style:'1',locale:document.documentElement.lang,allow_symbol_change:false,hide_side_toolbar:false,hide_top_toolbar:false,calendar:false,save_image:true,support_host:'https://www.tradingview.com'});script.onerror=()=>{$('liveStatus').textContent='TradingView could not load. Use the link to open this market chart.';goldWidgetInterval=null;};container.appendChild(script);host.appendChild(container);}
$('pair').addEventListener('change',showGoldChart);$('tf').addEventListener('change',()=>{if($('pair').value==='XAUUSD')$('live').disabled=true;showGoldChart();});$('pair').dispatchEvent(new Event('change'));
$('analyzeMarket').onclick=()=>{if(!rows){$('forecastDirection').textContent=$('pair').value==='XAUUSD'?'Gold forecast needs XAU/USD price history. Import a CSV to analyze the next 30 minutes.':'Start monitoring or import price history first.';return;}analyze();};
