(() => {
const select=document.getElementById('language'),status=document.getElementById('languageStatus');
const codes='aa ab ae af ak am an ar as av ay az ba be bg bh bi bm bn bo br bs ca ce ch co cr cs cu cv cy da de dv dz ee el en eo es et eu fa ff fi fj fo fr fy ga gd gl gn gu gv ha he hi ho hr ht hu hy hz ia id ie ig ii ik io is it iu ja jv ka kg ki kj kk kl km kn ko kr ks ku kv kw ky la lb lg li ln lo lt lu lv mg mh mi mk ml mn mr ms mt my na nb nd ne ng nl nn no nr nv ny oc oj om or os pa pi pl ps pt qu rm rn ro ru rw sa sc sd se sg si sk sl sm sn so sq sr ss st su sv sw ta te tg th ti tk tl tn to tr ts tt tw ty ug uk ur uz ve vi vo wa wo xh yi yo za zh zu'.split(' ');
const names=new Intl.DisplayNames(['en'],{type:'language'});for(const c of codes.sort((a,b)=>names.of(a).localeCompare(names.of(b)))){const o=document.createElement('option');o.value=c;o.textContent=names.of(c)+' ('+c+')';select.appendChild(o);}select.value='en';
// Explicit option values keep trading inputs independent of translated labels.
document.querySelectorAll('#tf option').forEach(o=>o.value=o.textContent);
let language='en',translator=null,revision=0,busy=false,pending=false,es={},cache=new Map();const sources=new WeakMap(),rendered=new WeakMap();
const eligible=n=>n.parentElement&&!n.parentElement.closest('script,style,[translate="no"],#goldWidget');
const observer=new MutationObserver(()=>{if(language!=='en')refresh();});const watch=()=>observer.observe(document.body,{subtree:true,childList:true,characterData:true});
async function translated(text){if(language==='en')return text;if(cache.has(text))return cache.get(text);let output=text;if(language==='es'){if(es[text]!==undefined)output=es[text];else for(const [en,sp]of Object.entries(es).sort((a,b)=>b[0].length-a[0].length))output=output.split(en).join(sp);}else output=await translator.translate(text);cache.set(text,output);return output;}
async function refresh(){if(busy){pending=true;return;}busy=true;const token=revision;try{const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode()){const n=walker.currentNode;if(!eligible(n)||!n.textContent.trim())continue;const last=rendered.get(n);if(!sources.has(n)||n.textContent!==last)sources.set(n,n.textContent);nodes.push(n);}const updates=[];for(const n of nodes){const before=n.textContent;updates.push([n,await translated(sources.get(n)),before]);}if(token!==revision)return;observer.disconnect();for(const [n,text,before]of updates){if(n.isConnected&&n.textContent===before){n.textContent=text;rendered.set(n,text);}}watch();}catch(e){status.textContent='Translation failed. Choose English to restore the page.';}finally{busy=false;if(pending){pending=false;refresh();}}}
select.onchange=async()=>{const next=select.value;revision++;const token=revision;status.textContent='';if(next==='en'){language='en';cache.clear();await refresh();document.documentElement.lang='en';document.documentElement.dir='ltr';localStorage.setItem('making-money-language','en');if(typeof showGoldChart==='function'){goldWidgetInterval=null;showGoldChart();}return;}
try{let newTranslator=null;if(next==='es'){if(!Object.keys(es).length){const r=await fetch('es.json?v=7');if(!r.ok)throw Error('Spanish dictionary unavailable.');es=await r.json();}}else {if(!('Translator'in window))throw Error('This browser cannot translate this language yet. English and Spanish are available.');const a=await Translator.availability({sourceLanguage:'en',targetLanguage:next});if(a==='unavailable')throw Error('This language is not supported by your browser. English and Spanish are available.');status.textContent='Preparing translation…';newTranslator=await Translator.create({sourceLanguage:'en',targetLanguage:next});}if(token!==revision){newTranslator?.destroy();return;}translator?.destroy();translator=newTranslator;language=next;cache.clear();await refresh();document.documentElement.lang=next;document.documentElement.dir=['ar','he','fa','ur','ps','sd','ug','yi'].includes(next)?'rtl':'ltr';status.textContent='';localStorage.setItem('making-money-language',next);
// TradingView renders its own controls using its supported locales.
if(typeof showGoldChart==='function'){goldWidgetInterval=null;showGoldChart();}
}catch(e){status.textContent=e.message;select.value=language;}};
watch();
})();
